### ISSUE TITLE
style.css Bug Report

### ISSUE THREAD

**Issue by Aidenlapinsky** [Aidenlapinsky/School#1]
Here are the bugs in the provided code:

1. The first line is empty and should be deleted.
2. In the `header` selector, the value of the `color` property is not a valid color value. It is missing a number after the last percentage sign. It should be a valid color value, for example, `hsl(206, 17%, 20%)`.
3. There is no closing brace for the `header` selector, which will cause a syntax error.

Here is the corrected code:

```css
*,
*:before,
*:after {
  box-sizing: border-box;
}

html,
body,
.wrapper {
  height: 100%;
  margin: 0;
  padding: 0;
}

body {
  font-family: sans-serif;
  background-color: #f9fbfd;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 0 20px;
}

.wrapper {
  width: 100%;
  max-width: 800px;
  padding: 30px 40px;
}

header {
  text-align: center;
  padding: 20px;
  color: hsl(206, 17%, 20%); /* corrected color value */
}
```
